#!/bin/sh
# This is an example wrapper script to be included in task package
set -e

TASK=toy
LANGU=c++17

if [ $# != 1 ] ; then
	echo >&2 "Usage $0 <source-file>"
	exit 1
fi

exec ioisubmit --lang=$LANGU $TASK "$1"
