#!/bin/sh
# This is an example wrapper script for an output-only task
set -e

TASK=toy

if [ $# != 1 ] ; then
	echo >&2 "Usage $0 <output-files>"
	exit 1
fi

exec ioisubmit --outputs="output_1 output_2 output_3" $TASK "$@"
